apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: web-port
    protocol: TCP
  selector:
    app: web-demo
  type: NodePort
